### ISSUE TITLE
Updates for Research.gov

### ISSUE THREAD

**Issue by glupyan** [CrumpLab/NSFrmarkdown#4]
Just thought I'd mention that NSF's Research.gov system to which they're transitioning from Fastlane now asks that page numbers not be added to the PDF (they're added by the system) and checks that the description have section headings "Intellectual Merit" and "Broader Impacts". (It's also throwing all sorts of margin and font size and line/in errors but these errors are incorrect. Waiting to hear back from their helpdesk about their PDF checker..)

**Comment by glupyan** [comment]
Figured out that the reason the margins are problematic is that beginning and end of line punctuation is intruding into the margins

**Comment by CrumpLab** [comment]
Thanks, not sure when I'll get to fixing this just yet...hopefully sooner than later

**Comment by glupyan** [comment]
No worries. Any idea how to keep the punctuation within the specified margins? That's the main issue.

**Comment by CrumpLab** [comment]
Just wondering how you figured out the margin issue? Was it by submitting and then looking at the errors from Research.gov? 

I just looked at the .pdf from the template, highlighted and saw that the punctuation on the right side runs a bit over, like this:

<img width="170" alt="Screen Shot 2019-07-26 at 12 11 09 PM" src="https://user-images.githubusercontent.com/4038982/61965663-b6ea1b00-af9e-11e9-8cd3-5d3f32c72dfb.png">

Is this one of the issues you are referring to?

**Comment by glupyan** [comment]
Precisely. The automatic margin checker at research.gov now picks this up and won't allow the submission (one solution is to just increase the margins everywhere, but this isn't ideal. Their helpdesk got back to be and confirmed that it was the punctuation that was throwing the errors.  It also runs over on the left if there's a left-justified punctuation mark such as a quote.

**Comment by CrumpLab** [comment]
Geez, what an annoying thing. I was going to suggest bringing the margins in a bit on both sides as a quick hack. Still searching for a Latex fix for this, have a few leads...hopefully they amount to something.

**Comment by CrumpLab** [comment]
Making some notes here that this issue has to do with "hanging punctuation" and protrusion into the margin...These terms seem to turn up relevant Latex commands...Still need to figure out how to turn it off.

**Comment by CrumpLab** [comment]
Ok, got a fix. Hopefully this doesn't break other things. I will update the repo shortly. The fix is to add the following to the nsf2.cls file in the style folder.

```
\usepackage[factor=0]{microtype}
```

**Comment by CrumpLab** [comment]
updated repo to disable hanging punctuation.

**Comment by CrumpLab** [comment]
Also, just turned off page numbering. The relevant lines in nsf2.cls are

Comment this to re-enable page numbering
```
\pagenumbering{gobble}
```
and

Uncomment this to re-enable page numbering
```
%\fancyfoot[R]{\thepage} 
```

**Comment by CrumpLab** [comment]
Closing this issue.
